repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.7.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        types:
          - css
          - javascript
          - html
          - vue
